-- 테스트 빌더가 migration의 public 참조를 performance_test 스키마로 바꿔 삽입한다.
-- 운영 주문 테이블/트리거에는 쓰지 않는다. 전체 테스트는 ROLLBACK으로 종료한다.
begin;
create schema performance_test;
create table performance_test.orders (
  id bigint primary key, user_id uuid, shipping_recipient_phone text,
  paid_at timestamptz, pg_approved_at timestamptz, created_at timestamptz,
  total_amount integer, refunded_amount integer, payment_status text, status text, attribution jsonb
);
create table performance_test.order_items (order_id bigint, quantity integer, refunded_at timestamptz,
  id bigint generated by default as identity, book_id bigint, unit_price integer, total_price integer);
create table performance_test.books (id bigint primary key, shipment_id bigint, brand text);
create table performance_test.shipments (id bigint primary key, pickup_date date, fee_policy_version text, is_direct_purchase boolean);
create table performance_test.settlements (id bigint primary key, order_id bigint, book_id bigint,
  sale_amount integer, fee_percent numeric, fee_amount integer, status text);
create function performance_test.is_admin_user() returns boolean language sql as
  $$ select current_setting('performance.is_admin',true) = 'true' $$;

-- @@PERFORMANCE_MIGRATION@@

select set_config('performance.is_admin','true',true);
insert into performance_test.orders(id,user_id,paid_at,created_at,total_amount,refunded_amount,payment_status,status,attribution) values
  (1,'11111111-1111-4111-8111-111111111111','2026-09-05 15:00Z','2026-09-01 10:00Z',10000,2000,'paid','confirmed','{"last_touch":{"source":"instagram","medium":"paid_social"}}'),
  (2,'11111111-1111-4111-8111-111111111111','2026-09-06 15:00Z','2026-09-06 15:00Z',5000,0,'paid','confirmed','{"last_touch":{"source":"instagram","medium":"social","click_id_types":["fbclid"]}}'),
  (3,null,'2026-09-07 15:00Z','2026-09-07 15:00Z',8000,0,'paid','preparing',null),
  (4,null,'2026-09-08 15:00Z','2026-09-08 15:00Z',9000,9000,'refunded','refunded',null),
  (5,null,null,'2026-09-08 15:00Z',1000000,0,'pending','cancelled',null),
  (6,null,'2026-09-05 14:59:59Z','2026-09-05 14:59:59Z',6000,0,'paid','confirmed',null),
  (7,null,'2026-09-12 15:00Z','2026-09-12 15:00Z',1000000,0,'paid','preparing',null),
  (8,null,null,'2026-09-09 15:00Z',1000000,0,'refunded','cancelled',null),
  (9,null,'2026-09-11 15:00Z','2026-09-11 15:00Z',3000,0,'refunded','refunded',null);
-- 같은 비회원의 포맷이 다른 연락처는 하나로 센다.
update performance_test.orders set shipping_recipient_phone = '010-0000-0001' where id=3;
update performance_test.orders set shipping_recipient_phone = '01000000001' where id=4;
insert into performance_test.order_items(order_id, quantity, refunded_at) values
  (1,3,null),(1,1,'2026-09-10 09:00Z'),(2,2,null),(3,1,null),(4,1,'2026-09-09 09:00Z'),
  (5,100,null),(6,2,null),(7,100,null),(8,100,null),(9,1,null);

do $test$
declare r jsonb; item jsonb; orders_count bigint;
begin
  r := performance_test.admin_performance_report('2026-09-06','2026-09-12');
  assert (r#>>'{current,grossRevenue}')::numeric = 35000, 'gross includes refunded, excludes unpaid and outside KST';
  assert (r#>>'{current,refunds}')::numeric = 14000, 'partial plus full refund fallback';
  assert (r#>>'{current,netRevenue}')::numeric = 21000;
  assert (r#>>'{current,orders}')::integer = 5, 'order join must not duplicate multi-item order';
  assert (r#>>'{current,repeatOrders}')::integer = 2, 'same member and normalized guest phone repeat';
  assert (r#>>'{current,repeatOrderRate}')::numeric = 40;
  assert (r#>>'{current,soldQuantity}')::integer = 6;
  assert (r#>>'{current,paidQuantity}')::integer = 9;
  assert (r#>>'{current,buyers}')::integer = 3, 'member dedupe, guest phone dedupe, missing contact fallback';
  assert (r#>>'{current,aov}')::numeric = 7000;
  assert (r#>>'{previous,grossRevenue}')::numeric = 6000;
  assert (r#>>'{previous,orders}')::integer = 1;
  assert (r#>>'{current,metaRevenue}')::numeric = 8000, 'organic Meta and fbclid alone are excluded';
  assert (r#>>'{current,metaOrders}')::integer = 1;
  assert (r#>>'{current,attributedOrders}')::integer = 2;
  assert (r->>'unverifiedPayments')::integer = 1;
  assert jsonb_array_length(r->'daily') = 7;
  assert (r#>>'{daily,0,date}') = '2026-09-06';
  assert (r#>>'{daily,0,orders}')::integer = 1;
  select sum((value->>'orders')::integer) into orders_count from jsonb_array_elements(r->'daily');
  assert orders_count=5, 'daily reconciles to summary';
  r := performance_test.admin_performance_report('2026-09-10','2026-09-10');
  assert (r#>>'{current,orders}')::integer = 0;
  assert (r#>'{current,aov}') = 'null'::jsonb, 'no-order AOV is unknown, not zero';
  assert (r#>'{current,repeatOrderRate}') = 'null'::jsonb;
  assert (r#>'{current,averageCommissionRate}') = 'null'::jsonb;
  assert jsonb_array_length(r->'daily')=1;
  begin perform performance_test.admin_performance_report('2026-09-12','2026-09-01'); raise exception 'range guard failed'; exception when invalid_parameter_value then null; end;
  begin perform performance_test.admin_performance_report('2025-01-01','2026-09-12'); raise exception 'limit guard failed'; exception when invalid_parameter_value then null; end;
  begin perform performance_test.admin_performance_report(null,'2026-09-12'); raise exception 'null guard failed'; exception when invalid_parameter_value then null; end;
  assert not has_function_privilege('anon','performance_test.admin_performance_report(date,date)','execute'), 'anon denied';
  perform set_config('performance.is_admin','false',true);
  begin perform performance_test.admin_performance_report('2026-09-06','2026-09-12'); raise exception 'admin guard failed'; exception when insufficient_privilege then null; end;
  perform set_config('performance.is_admin','true',true);
end;
$test$;

-- 여러 정책이 섞인 실제 판매 구성. 운영 테이블/트리거에는 접근하지 않는다.
insert into performance_test.shipments values
  (1,'2026-01-20',null,false),(2,'2026-09-15','2026-09',false),
  (3,'2026-03-01',null,false),(4,'2026-09-15','2026-09',true);
insert into performance_test.books values
  (1,1,'시대인재'),(2,2,'시대인재'),(3,null,'전일학원'),
  (4,4,'기타'),(5,2,'시대인재'),(6,2,'시대인재'),(7,3,'시대인재'),(8,1,'시대인재');
insert into performance_test.orders(id,user_id,paid_at,total_amount,payment_status,status) values
  (100,'22222222-2222-4222-8222-222222222222','2026-07-01 00:00Z',8000,'refunded','refunded'),
  (101,'22222222-2222-4222-8222-222222222222','2026-08-20 00:00Z',16000,'paid','confirmed'),
  (102,'22222222-2222-4222-8222-222222222222','2026-08-20 00:00Z',30000,'paid','preparing'),
  (103,null,'2026-08-20 01:00Z',59000,'paid','preparing'),
  (104,null,'2026-08-20 01:00Z',9000,'refunded','refunded'),
  (105,null,'2026-08-20 02:00Z',12000,'paid','preparing'),
  (106,null,'2026-08-20 03:00Z',20000,'paid','confirmed'),
  (107,null,'2026-08-20 04:00Z',9000,'paid','preparing'),
  (108,null,'2026-08-20 05:00Z',19000,'paid','confirmed'),
  (109,'22222222-2222-4222-8222-222222222222','2026-06-01 00:00Z',5000,'pending','cancelled'),
  (110,null,null,9000,'paid','confirmed'),
  (111,null,'2026-07-01 01:00Z',9000,'paid','confirmed'),
  (112,'22222222-2222-4222-8222-222222222222','2026-08-19 05:00Z',3000,'paid','confirmed');
update performance_test.orders set shipping_recipient_phone='010-1234-5678' where id=103;
update performance_test.orders set shipping_recipient_phone='01012345678' where id=104;
insert into performance_test.order_items(order_id,book_id,quantity,unit_price,total_price,refunded_at) values
  (101,1,2,8000,16000,null),(102,2,3,10000,30000,null),(103,3,1,59000,59000,null),
  (104,3,1,9000,9000,null),(105,4,1,12000,12000,null),
  (106,5,1,20000,20000,null),(107,6,1,9000,9000,null),
  (108,7,1,10000,10000,null),(108,8,1,9000,9000,'2026-08-21 00:00Z');
insert into performance_test.settlements values
  (1,106,5,20000,31.25,6250,'completed'),
  (2,102,2,30000,10,3000,'cancelled');

do $test$
declare r jsonb; c jsonb; d jsonb;
begin
  r := performance_test.admin_performance_report('2026-08-20','2026-08-20');
  c := r->'current'; d := r#>'{daily,0}';
  assert (c->>'orders')::integer = 8;
  assert (c->>'repeatOrders')::integer = 3, 'historical/refunded purchases, tied timestamp, guest normalization';
  assert (c->>'repeatOrderRate')::numeric = 37.5;
  assert (r#>>'{previous,repeatOrders}')::integer = 1, 'comparison also sees full history';
  assert (r#>>'{previous,repeatOrderRate}')::numeric = 100;
  assert (c->>'commissionSales')::numeric = 144000, 'quantity weighted, refunded/unknown excluded';
  assert (c->>'commissionAmount')::numeric = 63350, 'legacy 35/40, new 45/50, Jeonil 50, stored 31.25';
  assert abs((c->>'averageCommissionRate')::numeric - 63350.0/144000*100) < 0.000001;
  assert (c->>'commissionExcludedQuantity')::integer = 1;
  assert (d->>'commissionSales') = (c->>'commissionSales');
  assert (d->>'commissionAmount') = (c->>'commissionAmount');
  assert (d->>'averageCommissionRate') = (c->>'averageCommissionRate');
  assert (d->>'repeatOrders') = (c->>'repeatOrders');
  assert jsonb_array_length(r->'commissionBreakdown') = 7;
  assert (select sum((v->>'feeAmount')::numeric) from jsonb_array_elements(r->'commissionBreakdown') v) = 63350;
  assert not r::text like '%22222222-2222%', 'customer identity never leaves RPC';
  r := performance_test.admin_performance_report('2026-08-01','2026-08-01');
  assert (r#>'{current,averageCommissionRate}') = 'null'::jsonb;
  assert r->'commissionBreakdown' = '[]'::jsonb;
end;
$test$;

select 'PASS: KST boundaries, comparison, quantities, refund, buyer dedupe, attribution, empty period, validation, admin/anon guards' as result;
rollback;
